name: webrtsp-camera-streamer
base: core24
summary: Streams video from camera to browser
adopt-info: restreamer
description: |
  Can be used to turn your Raspberry Pi with attached CSI-2 Camera into WebRTSP IP Camera.
  Supports any camera device supported by libcamera.
  Can act as remote Agent for WebRTSP server (https://snapcraft.io/rtsp-to-webrtsp)

  To try, install snap and open http://localhost:5080 in your browser.

  **Config file location:** /var/snap/webrtsp-camera-streamer/common/camera-streamer.conf

license: GPL-3.0
grade: devel
confinement: strict

platforms:
  arm64:
#  armhf: # libx264 requires exacstack on armhf
#  amd64:

layout:
  /opt/${CRAFT_PROJECT_NAME}/lib:
    symlink: $SNAP/opt/${CRAFT_PROJECT_NAME}/lib
  /opt/${CRAFT_PROJECT_NAME}/share/libcamera:
    symlink: $SNAP/opt/${CRAFT_PROJECT_NAME}/share/libcamera

parts:
  meson-deps:
    plugin: python
    source: .
    python-packages:
      - meson
      - ninja
      - jinja2
      - pyyaml
      - ply
  gstreamer:
    plugin: meson
    source: https://github.com/GStreamer/gstreamer.git
    source-branch: 1.28
    after:
      - meson-deps
    build-packages:
      - flex
      - bison
      - nasm
      - libsrtp2-dev
    meson-parameters:
      - --prefix=/opt/${SNAPCRAFT_PROJECT_NAME}
      - --buildtype=release
      - -Dbase=enabled
      - -Dgood=enabled
      - -Dbad=enabled
      - -Dugly=enabled
      - -Dlibav=disabled
      - -Ddevtools=disabled
      - -Dges=disabled
      - -Drtsp_server=disabled
      - -Dgst-examples=disabled
      - -Dpython=disabled
      - -Dgpl=disabled
      - -Dbenchmarks=disabled
      - -Dtools=disabled
      - -Dqt5=disabled
      - -Dqt6=disabled
      - -Dtests=disabled
      - -Dexamples=disabled
      - -Dintrospection=disabled
      - -Dnls=disabled
    stage-packages:
      - libunwind8
      - libdw1
      - libupnp17t64
      - libgupnp-igd-1.6-0
      - libsrtp2-1
  libcamera:
    plugin: meson
    source: https://github.com/raspberrypi/libcamera.git
    source-branch: v0.7.0+rpt20260205
    after:
      - meson-deps
      - gstreamer
    build-packages:
      - meson
      - g++
      - ninja-build
      - libyaml-dev
      - libssl-dev
      - openssl
      - libevent-dev
    build-environment:
      - PKG_CONFIG_PATH: ${CRAFT_STAGE}/opt/${CRAFT_PROJECT_NAME}/lib/pkgconfig:${CRAFT_STAGE}/opt/${CRAFT_PROJECT_NAME}/lib/${CRAFT_ARCH_TRIPLET_BUILD_ON}/pkgconfig:${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}
    meson-parameters:
      - --prefix=/opt/${CRAFT_PROJECT_NAME}
      - -Dcam=disabled
      - -Ddocumentation=disabled
      - -Dgstreamer=enabled
      - -Dlc-compliance=disabled
      - -Dpycamera=disabled
      - -Dqcam=disabled
      - -Dtest=false
      - -Dtracing=disabled
      - -Dudev=disabled
    stage-packages:
      - libevent-2.1-7
      - libevent-pthreads-2.1-7
  restreamer:
    plugin: cmake
    source-type: git
    source: https://github.com/WebRTSP/ReStreamer.git
    build-environment:
      - PKG_CONFIG_PATH: ${CRAFT_STAGE}/opt/${CRAFT_PROJECT_NAME}/lib/pkgconfig:${CRAFT_STAGE}/opt/${CRAFT_PROJECT_NAME}/lib/${CRAFT_ARCH_TRIPLET_BUILD_ON}/pkgconfig:${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
      - LD_LIBRARY_PATH: ${CRAFT_STAGE}/opt/${CRAFT_PROJECT_NAME}/lib/${CRAFT_ARCH_TRIPLET_BUILD_ON}:${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/opt/${CRAFT_PROJECT_NAME}
      - -DCAMERA_STREAMER=ON
    override-pull: |
        craftctl default
        craftctl set version="$(git describe --always)"
    after:
      - gstreamer
      - libcamera
    build-snaps:
      - node/24/stable
    build-packages:
      - g++
      - ninja-build
      - libspdlog-dev
      - libconfig-dev
      - libmicrohttpd-dev
      - libwebsockets-dev
    stage-packages:
      - libconfig9
      - libx264-164
      - libspdlog1.12
      - libmicrohttpd12
      - libwebsockets19t64
      - libwebsockets-evlib-glib
apps:
  CameraStreamer:
    command: opt/${CRAFT_PROJECT_NAME}/bin/CameraStreamer
    daemon: simple
    plugs:
      - network-bind
      - network
      - camera
      - media-control
      - opengl
    environment:
      LD_LIBRARY_PATH: $SNAP/opt/${SNAP_NAME}/lib:$SNAP/opt/${SNAP_NAME}/lib/${CRAFT_ARCH_TRIPLET_BUILD_ON}:${LD_LIBRARY_PATH}
      LIBCAMERA_LOG_LEVELS: 4
      GST_DEBUG: 2
      GST_DEBUG_NO_COLOR: 1
      GST_PLUGIN_PATH: $SNAP/opt/${SNAP_NAME}/lib/${CRAFT_ARCH_TRIPLET_BUILD_ON}/gstreamer-1.0
      GST_PLUGIN_SYSTEM_PATH: $SNAP/opt/${SNAP_NAME}/lib/${CRAFT_ARCH_TRIPLET_BUILD_ON}/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/opt/${SNAP_NAME}/libexec/gstreamer-1.0/gst-plugin-scanner
